# Conda environment file for captest v0.5*
# To create a conda environment using this file:
# conda env create -f captest_env.yml
# includes all requirements to run captest and build docs
# Does not include all packages needed for testing
name: captest_env_05
channels:
- conda-forge
- defaults
dependencies:
- bokeh=1.3.4
- holoviews=1.12.5
- matplotlib=3.0.3
- numpy=1.16.4
- pandas=0.24.2
- pip
- python=3.7*
- python-dateutil=2.8.0
- statsmodels=0.10.1
- scikit-learn=0.21.2
- scipy=1.2.1
- docutils=0.15.2
- ipykernel=5.1.2
- ipython=7.7.0
- jupyter=1.0.0
- jupyter_client=5.3.1
- jupyter_console=6.0.0
- jupyter_core=4.5.0
- nbsphinx=0.4.2
- notebook=6.0.0
- sphinx_rtd_theme=0.4.3
- pip:
  - commonmark==0.9.0
  - pvlib==0.6.3
  - recommonmark==0.6.0
  - sphinx==2.2.0
  - tables==3.5.2
  - captest==0.5.3
