name: pvc_env
dependencies:
- python=3.5*
- pandas=0.23.3
- numpy=1.15
- python-dateutil=2.7.3
- matplotlib=2*
- statsmodels=0.8*
- scikit-learn=0.19.1
- seaborn=0.9.0
- bokeh=0.13.0
- ipython-notebook*
- ipython*
- pip:
  - captest
